FROM nimmis/alpine-apache
LABEL Author="eboda"
COPY files/ /tmp/
RUN apk add --no-cache apache2 php7-mbstring &&\
    #Base infastructure
    mkdir /var/www/localhost/htdocs/images &&\
    mv /tmp/conf/php.ini /etc/php7/ &&\
    mv /tmp/conf/httpd.conf /etc/apache2/httpd.conf &&\
    #Conf files
    mv /tmp/app/ /var/www/localhost/htdocs/ &&\
    mv /tmp/get_flag /tmp/flag / &&\
    chmod 400 /flag &&\
    chmod u+s+x /get_flag &&\
    rm /var/www/localhost/htdocs/index.html &&\
    chown -R apache:apache /var/www/localhost/htdocs/
    #Source files
ENTRYPOINT ["httpd","-D","FOREGROUND"]
EXPOSE 80